# Site settings
title: Thesis Project Blog
email: mljenior@umich.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mjenior.github.io" # the base hostname & protocol for your site
twitter_username: mljenior
github_username:  mjenior

# Build settings
markdown: kramdown
