title:            Matt Jenior
description:      A site about projects and science I have worked with
disqus_shortname: mjwebsite
reading_time:     false
words_per_minute: 
url: http://mjenior.github.io/

owner:
  name:           Matthew Jenior
  avatar:         avatar.jpg
  bio:            "I'm an experienced computational biologist who combines large-scale machine learning analyses and multi-omics with expertise across in vivo, in vitro, & in silico systems. I rapidly move projects from concept to delivery, having a track record of creatively applying bioinformatic & data science techniques across projects in infectious disease, molecule bioproduction, cancer biology, drug discovery, & agriculture. Ultimately providing meaningful, & actionable results to diverse groups of clients."
  email:          mattjenior@gmail.com
  github:         mjenior

# Background image to be tiled on all pages
background: black.jpg

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:           

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Vancouver
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 2

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
