# Site settings
title: Thesis Project Blog
email: mljenior@umich.edu
name: Research blog
description: A blog about progress on my research
url: http://mjenior.github.io
twitter_username: mljenior
github_username:  mjenior

# Build settings
markdown: kramdown
